-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE P, REST_REVIEW R,
(SELECT COUNT(MEMBER_ID) AS CT, MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID) T
WHERE P.MEMBER_ID = R.MEMBER_ID AND P.MEMBER_ID=T.MEMBER_ID AND
P.MEMBER_ID in (SELECT TS.MEMBER_ID FROM 
    (SELECT COUNT(MEMBER_ID) AS CT, MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID) TS
        WHERE TS.CT = (SELECT MAX(TK.CT) FROM
              (SELECT COUNT(MEMBER_ID) AS CT, MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID) TK
))
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;
