SELECT K.FLAVOR
FROM(
SELECT T.FLAVOR, SUM(T.S)
FROM(SELECT H.FLAVOR, SUM(H.TOTAL_ORDER) AS S
FROM FIRST_HALF H
GROUP BY H.FLAVOR
UNION ALL
SELECT J.FLAVOR,SUM(J.TOTAL_ORDER) AS S
FROM JULY J
GROUP BY J.FLAVOR) T
GROUP BY T.FLAVOR
ORDER BY SUM(T.S) DESC
) K
WHERE ROWNUM<=3;
