-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P,DOCTOR D,APPOINTMENT A
WHERE P.PT_NO = A.PT_NO AND A.MDDR_ID = D.DR_ID AND
D.MCDP_CD = 'CS' AND A.APNT_CNCL_YN = 'N' AND TO_CHAR(A.APNT_YMD,'YYYYMMDD') LIKE ('%20220413%');
