-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, CASE
        WHEN STATUS LIKE ('%SALE%') THEN '판매중'
        WHEN STATUS LIKE ('%DONE%') THEN '거래완료'
        ELSE '예약중' END AS STATUS
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE,'YYYYMMDD') IN ('20221005')
ORDER BY BOARD_ID DESC;
