-- 코드를 입력하세요
SELECT MCDP_CD AS 진료과코드, COUNT(TO_CHAR(APNT_YMD,'YYYYMM')) AS "5월예약건수"
FROM APPOINTMENT
WHERE TO_CHAR(APNT_YMD,'YYYYMM') IN ('202205')
GROUP BY MCDP_CD
ORDER BY COUNT(TO_CHAR(APNT_YMD,'YYYYMM')) ASC,
         MCDP_CD ASC;
