-- 코드를 입력하세요
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS,
       TO_CHAR(UGR.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD UGB, USED_GOODS_REPLY UGR
WHERE TO_CHAR(UGB.CREATED_DATE,'YYYYMM') = '202210' AND
      UGR.BOARD_ID = UGB.BOARD_ID
ORDER BY UGR.CREATED_DATE, UGB.TITLE ASC;
