SELECT A.ANIMAL_ID, A.NAME
FROM(
    SELECT I.ANIMAL_ID, I.NAME,(TO_CHAR(O.DATETIME,'YYYYMMDD')-TO_CHAR(I.DATETIME,'YYYYMMDD')) AS DATETIME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID=O.ANIMAL_ID
    ORDER BY DATETIME DESC
) A
WHERE ROWNUM <=2;
